name:                crossref-verifier
version:             0.1.0.0
github:              serokell/crossref-verifier
license:             MPL-2.0
license-file:        LICENSE
author:              Kostya Ivanov, Serokell
maintainer:          Serokell <hi@serokell.io>
copyright:           2018-2019 Serokell <https://serokell.io>

extra-source-files:
- README.md
- src-files/*

description:         Please see the README on GitHub at <https://github.com/serokell/crossref-verifier#readme>

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - UndecidableInstances
  - ViewPatterns
  - TypeApplications
  - TypeOperators

build-tools:
  - autoexporter

ghc-options:
  - -Wall
  - -Wincomplete-record-updates

dependencies:
  - aeson
  - aeson-options
  - async
  - base-noprelude
  - bytestring
  - containers
  - cmark-gfm
  - data-default
  - deepseq
  - directory-tree
  - directory
  - filepath
  - fmt
  - Glob
  - http-client
  - http-types
  - lens
  - loot-prelude
  - pretty-terminal
  - mtl
  - o-clock
  - optparse-applicative
  - req
  - roman-numerals
  - template-haskell
  - text
  - text-metrics
  - th-lift-instances
  - th-utilities
  - yaml

library:
  source-dirs: src

executables:
  crossref-verify:
    main:                Main.hs
    source-dirs:         exec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - crossref-verifier

tests:
  crossref-verifier-tests:
    main:                Main.hs
    source-dirs:         tests
    dependencies:
    - crossref-verifier
    - hspec
    - QuickCheck
    build-tools:
    - hspec-discover
