# SPDX-FileCopyrightText: 2018-2020 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-19.13

packages:
- .

extra-deps:
- roman-numerals-0.5.1.5
- firefly-0.2.1.0@sha256:e9d73486464c3e223ec457e02b30ddd5b550fdbf6292b268c64581e2b07d888b,1519
- git: https://github.com/kivikakk/cmark-gfm-hs
  commit: 205f820fd3ca0aefde1d4fdbea30a5e593295c3b
