# SPDX-FileCopyrightText: 2018-2020 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-19.13

packages:
- .

extra-deps:
- firefly-0.2.1.0@sha256:e9d73486464c3e223ec457e02b30ddd5b550fdbf6292b268c64581e2b07d888b,1519
- cmark-gfm-0.2.5
- git: https://github.com/serokell/nyan-interpolation
  commit: 5e158057b167275d2150454e2bb731cfe686ea7a
  subdirs:
  - full
  - core
