# SPDX-FileCopyrightText: 2018-2020 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-17.3

packages:
- .

extra-deps:
- pretty-terminal-0.1.0.0
- roman-numerals-0.5.1.5
- with-utf8-1.0.2.2
- th-utilities-0.2.4.0@sha256:ba19cd8441aa43dbaed40e9055bb5a7cbd7cf9e154f5253c6bf9293af8b1f96b,1869
