# SPDX-FileCopyrightText: 2018-2019 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

resolver: lts-14.16

packages:
- .

extra-deps:
- pretty-terminal-0.1.0.0
- roman-numerals-0.5.1.5
- aeson-options-0.1.0
- o-clock-1.1.0
- with-utf8-1.0.0.0
