resolver: lts-14.16

packages:
- .

extra-deps:
- pretty-terminal-0.1.0.0
- roman-numerals-0.5.1.5
- aeson-options-0.0.0
- o-clock-1.0.0.1

- git: https://github.com/serokell/lootbox.git
  commit: 34e389808e34f1cfa56f456773682325bed56d17
  subdirs:
    - code/prelude
