resolver: lts-14.16

packages:
- .

extra-deps:
- pretty-terminal-0.1.0.0
- roman-numerals-0.5.1.5
- aeson-options-0.1.0
- o-clock-1.1.0

- git: https://github.com/serokell/lootbox.git
  commit: 4700376b8493f6ac164461715cb72a0259148ac2 # master
  subdirs:
    - code/prelude
