name: CI

on:
  pull_request:
  push:

jobs:
  static:
    name: Build the static executable
    runs-on: nixos
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: nix-build ci.nix -A xrefcheck-static
